declare module 'deck.gl'
declare module '@deck.gl/react'
declare module '@deck.gl/geo-layers'
declare module '@deck.gl/layers'
declare module '@math.gl/core'
declare module '@loaders.gl/core'
declare module '@loaders.gl/images'