#!/bin/bash
# This file was automatically generated by jinjaroot. Do not edit directly. See the .jinjaroot dir.


set -ex

cd .git/hooks
rm -f pre-commit
ln -s ../../devel/githooks/pre-commit pre-commit